NET='*'
INET='*'
NET_IPIP='*M'
NET_IPGRE_DEMUX='*M'
NET_IPGRE='*M'
IPV6='*'
IPV6_SIT='*M'
IPV6_GRE='*M'
IPV6_MULTIPLE_TABLES='*'
MPTCP='*'
MPTCP_IPV6='*'
VLAN_8021Q='*M'
NET_SCHED='*'
NET_SCH_SFQ='*'
NET_SCH_TBF='*'
NET_SCH_FQ_CODEL='*'
NET_SCH_INGRESS='*'
NETDEVICES='*'
NET_CORE='*'
BONDING='*M'
DUMMY='*M'
NET_TEAM='*M'
MACVLAN='*M'
MACVTAP='*M'
IPVLAN='*M'
VXLAN='*M'
VETH='*M'
NET_VRF='*M'
