# forced by !EXPERT
BLOCK = { value = '*', forced = true }
EFI='*'
EFI_STUB='*'
PARTITION_ADVANCED='* '
EFI_PARTITION="*"
SYSFB_SIMPLEFB="*"
DRM="*"
DRM_FBDEV_EMULATION="*"
DRM_SIMPLEDRM="*"
FRAMEBUFFER_CONSOLE = '*'
VFAT_FS="*M"
EFIVAR_FS="*M"
# forced by both ACPI and PCI on a typical x86 desktop/server system
NLS = { value = "*", forced = "*" }
NLS_CODEPAGE_437="*M"
NLS_ISO8859_1="*M"
