USB_SUPPORT='*'
USB='*M'
USB_PCI='*'

USB_EHCI_HCD='*M '
USB_OHCI_HCD='*M '

[USB_XHCI_HCD]
value = '*M '
comment = [
	'These are most common USB controller drivers for PC-like systems.',
	'For modern systems often [USB_XHCI_HCD] is the only one needed',
	'even if the system has USB 2.0 ports'
]
